import tkinter
from tkinter import *
from tkinter import messagebox
from tkinter import ttk
import pymysql
def escfind():
    t=tkinter.Tk()
    t.geometry('700x700')
    t.title('ESCALATION FIND')
    t.config(bg='pink')
    def fillids():
        x=[]
        db=pymysql.connect(host='localhost',user='root',password='youtube',database='testdb')
        cur=db.cursor()
        sql="select studid from escalation"
        cur.execute(sql)
        data=cur.fetchall()
        for res in data:
            x.append(res[0])
        return x
    def finddata():
        x=a1.get()
        db=pymysql.connect(host='localhost',user='root',password='youtube',database='testdb')
        cur=db.cursor()
        sql="select Teacherid,Majorsub,Rating,Dateoffeedback,Remark,Comment from escalation where studid='%s'"%(x)
        cur.execute(sql)
        data=cur.fetchone()
        if data==None:
            messagebox.showerror("Error",'Data Not Found')
        else:
            b1.delete(0,100)
            c1.delete(0,100)
            d1.delete(0,100)
            e1.delete(0,100)
            f1.delete(0,100)
            g1.delete(0,100)
            b1.insert(0,data[0])
            c1.insert(0,data[1])
            d1.insert(0,data[2])
            e1.insert(0,data[3])
            f1.insert(0,data[4])
            g1.insert(0,data[5])
    def clear():
        a1.delete(0,100)
        b1.delete(0,100)
        c1.delete(0,100)
        d1.delete(0,100)
        e1.delete(0,100)
        f1.delete(0,100)
        g1.delete(0,100)
    s=Label(t,text='ESCALATION FIND',font=40,fg='black',bg='pink')
    s.place(x=275,y=50)
    a=Label(t,text='Student Id',font=20,bg='light blue')
    a.place(x=75,y=125)
    a1=ttk.Combobox(t,width=10)
    a1.place(x=250,y=125)
    idlist=fillids()
    a1['values']=idlist
    b=Label(t,text='Teacher Id',font=20,bg='light blue')
    b.place(x=75,y=175)
    b1=Entry(t,width=40)
    b1.place(x=250,y=175)
    c=Label(t,text='Major Subject',font=20,bg='light blue')
    c.place(x=75,y=225)
    c1=Entry(t,width=40)
    c1.place(x=250,y=225)
    d=Label(t,text='Rating',font=20,bg='light blue')
    d.place(x=75,y=275)
    d1=Entry(t,width=40)
    d1.place(x=250,y=275)
    e=Label(t,text='Date of feedback',font=20,bg='light blue')
    e.place(x=75,y=325)
    e1=Entry(t,width=40)
    e1.place(x=250,y=325)
    f=Label(t,text='Remarks',font=20,bg='light blue')
    f.place(x=75,y=375)
    f1=Entry(t,width=40)
    f1.place(x=250,y=375)
    g=Label(t,text='Comment',font=20,bg='light blue')
    g.place(x=75,y=425)
    g1=Entry(t,width=40)
    g1.place(x=250,y=425)
    bt1=Button(t,text='FIND',bg='green',command=finddata)
    bt1.place(x=270,y=500)
    bt2=Button(t,text='CLEAR',bg='green',command=clear)
    bt2.place(x=370,y=500)
    t.mainloop()
