import tkinter
from tkinter import *
from tkinter import messagebox
import pymysql
from tkinter import ttk
def studentregisterdelete():
    t=tkinter.Tk()
    t.geometry('700x700')
    t.title('STUDENT REGISTER DELETE')
    t.config(bg='light green')
    def fillids():
        x=[]
        db=pymysql.connect(host='localhost',user='root',password='youtube',database='testdb')
        cur=db.cursor()
        sql="select studid from studentregister"
        cur.execute(sql)
        data=cur.fetchall()
        for res in data:
            x.append(res[0])
        return x
    def finddata():
        x=a1.get()
        db=pymysql.connect(host='localhost',user='root',password='youtube',database='testdb')
        cur=db.cursor()
        sql="select studentname,address,city,email,depid from studentregister where studid='%s'"%(x)
        cur.execute(sql)
        data=cur.fetchone()
        if data==None:
            messagebox.showerror("Error",'Data Not Found')
        else:
            b1.delete(0,100)
            c1.delete(0,100)
            d1.delete(0,100)
            e1.delete(0,100)
            f1.delete(0,100)
            b1.insert(0,data[0])
            c1.insert(0,data[1])
            d1.insert(0,data[2])
            e1.insert(0,data[3])
            f1.insert(0,data[4])
    def deletedata():
        x=a1.get()
        db=pymysql.connect(host='localhost',user='root',password='youtube',database='testdb')
        cur=db.cursor()
        sql="delete from studentregister where studid='%s'"%(x)
        cur.execute(sql)
        a1.delete(0,100)
        db.commit()
        db.close()
        messagebox.showinfo("Deleted","Record Deleted..")   
    def clear():
        a1.delete(0,100)
        b1.delete(0,100)
        c1.delete(0,100)
        d1.delete(0,100)
        e1.delete(0,100)
        f1.delete(0,100)
    s=Label(t,text='STUDENT REGISTER DELETE',font=40,fg='black',bg='red')
    s.place(x=150,y=50)
    a=Label(t,text='Student id',font=20,bg='green')
    a.place(x=75,y=125)
    a1=ttk.Combobox(t,width=27)
    a1.place(x=250,y=125)
    idlist=fillids()
    a1['values']=idlist
    b=Label(t,text='Student name',font=20,bg='green')
    b.place(x=75,y=175)
    b1=Entry(t,width=30)
    b1.place(x=250,y=175)
    c=Label(t,text='Depid',font=20,bg='green')
    c.place(x=75,y=225)
    c1=Entry(t,width=30)
    c1.place(x=250,y=225)
    d=Label(t,text='Address',font=20,bg='green')
    d.place(x=75,y=275)
    d1=Entry(t,width=30)
    d1.place(x=250,y=275)
    e=Label(t,text='City',font=20,bg='green')
    e.place(x=75,y=325)
    e1=Entry(t,width=30)
    e1.place(x=250,y=325)
    f=Label(t,text='Email',font=20,bg='green')
    f.place(x=75,y=375)
    f1=Entry(t,width=30)
    f1.place(x=250,y=375)
    bt=Button(t,text='FIND',bg='orange',command=finddata)
    bt.place(x=150,y=450,height=40,width=80)
    bt1=Button(t,text='DELETE',bg='orange',command=deletedata)
    bt1.place(x=250,y=450,height=40,width=80)
    bt2=Button(t,text='CLEAR',bg='orange',command=clear)
    bt2.place(x=350,y=450,height=40,width=80)
    t.mainloop()